[package]
name = "xml-builder"
version = "0.2.2"
authors = ["LIAUD Corentin <corentin.liaud@orange.fr>"]
description = "XML builder/writer"
readme = "README.md"
license = "MIT"
edition = "2018"
repository = "https://github.com/cocool97/xml-builder"

[dependencies]
